### ISSUE TITLE
Unable to get inputs from user and move player

### ISSUE THREAD

**Issue by User-92** [touilleMan/godot-python#216]
I was making a player controller, when I ran into this:
![errors](https://user-images.githubusercontent.com/51941595/87160968-73f58600-c289-11ea-92ff-6d8b916d39cb.png)
Full error:
```
E 0:00:00.470   _physics_process: 
Traceback (most recent call last):
  File "build/x11-64/pythonscript/_godot_instance.pxi", line 98, in _godot.pythonscript_instance_call_method
  File "/home/user/PyScript-Test/Player.py", line 22, in _physics_process
    move_and_slide(self.direction, Vector3(0, 1, 0))
NameError: name 'move_and_slide' is not defined

  <C++ Source>  /home/user/PyScript-Test/Player.py:22 @ _physics_process()
```

This is my code:
![code](https://user-images.githubusercontent.com/51941595/87161173-bdde6c00-c289-11ea-8f74-276a07c05503.png)

I also tried without the self.direction and self.speed, but the same thing happened. If I remove the move_and_slide function, I don't get any errors, so it's coming from the move_and_slide function.

I also moved the self.direction and the self.speed variable outside of the class (as speed and as direction), but it still gave me the error.

I can give you move information if it is required.

Can anyone help me with this?

**Comment by User-92** [comment]
Oh, I found my issue. I needed to add self. in front of move_and_slide
