### ISSUE TITLE
Error trying to test

### ISSUE THREAD

**Issue by bruno-ortizgb** [touilleMan/godot-python#23]
Hello, im trying to test the module but i keep getting the following error:

ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.

What am i doing wrong?

thx

**Comment by touilleMan** [comment]
It seems your python file is not valid (error in syntax or you forget to mark a class inheriting from a Godot Node class as `@exposed`). Did you get any other errors before this one ?

**Comment by bruno-ortizgb** [comment]
No the code that this happens is the default template.

```python
from godot import exposed, export
from godot.bindings import *


@exposed
class MyExportedCls(Node2D):

    # member variables here, example:
    a = export(int)
    b = export(str)

    def _ready(self):
        pass
```

**Comment by bruno-ortizgb** [comment]
Just to give you more context, this happens after i attach the script to a Node2D and click in the TreeNode.

This is the full log

```
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_property_default_value: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:314.
ERROR: get_script_signal_list: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:728.
ERROR: get_script_signal_list: Cannot retrieve Python class for this script, is you code correct ?
   At: modules/pythonscript/py_script.cpp:728.
```

And when i run "make tests", this is the result:

```
cd tests/bindings && `ls /home/bruno/repository/godot-python/godot/bin/godot* | head -n 1` 
GLES3: max extensions: 170
hdr supported: 1
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_cffi_backend'

From: pythonscriptcffi
compiled with cffi version: 1.10.0
_cffi_backend module: not loaded
sys.path: ['/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages']

function pythonscriptcffi.pybind_init_sys_path_and_argv() called, but initialization code failed.  Returning 0.
ERROR: init: Method/Function Failed.
   At: modules/pythonscript/py_language.cpp:29.
WARNING: not found: locale/translation_remaps
function pythonscriptcffi.pybind_load_exposed_class_per_module() called, but initialization code failed.  Returning 0.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/pythonscript/py_script.cpp:190.
```

**Comment by touilleMan** [comment]
I've made more tests and I think this issue could be related with the way Python does it bootstrap inside Godot.
Basically I use and init function written in python that set the `sys.path` (where to look for python modules).
However to call this function cffi must initialize itself first, which means loading the cffi module...
So if cffi module (i.e. `_cffi_backend.cpython-36m-x86_64-linux-gnu.so`) is not available in the default `PYTHONPATH`, Python fails with `_cffi_backend module: not loaded`.

**Comment by touilleMan** [comment]
PYTHONHOME is much better handled now, should no longer be an issue
