### ISSUE TITLE
Error using numba package: "TypeError: not enough arguments for format string"

### ISSUE THREAD

**Issue by thetoblin** [touilleMan/godot-python#244]
Following the successful installation of godot-python master in the following thread: https://github.com/touilleMan/godot-python/issues/238, I am now able to import the numba package in godot-python.

However, as I try to run the code below (test.py), I run into the error `TypeError: not enough arguments for format string`. I get the error both when I try to run it from within Godot and when I run it using the python installation in godot-python through a terminal (see below). **The example code works to run in my normal python environment, which suggests that there is something off about the godot-python compilation.**

Another symptom that I suspect is connected is that when I run an interactive shell of the godot-python python installation is that hitting backspace prints an empty space (it doesn't erase chars as expected, but appends empty space to the command line).

Any ideas? 

```python
# test.py -> the code I try to run
from numba import cuda, float32
import numpy
import math

# Controls threads per block and shared memory usage.
# The computation will be done on blocks of TPBxTPB elements.
TPB = 16

@cuda.jit
def fast_matmul(A, B, C):
    """
    Perform matrix multiplication of C = A * B
    Each thread computes one element of the result matrix C
    """

    # Define an array in the shared memory
    # The size and type of the arrays must be known at compile time
    sA = cuda.shared.array(shape=(TPB, TPB), dtype=float32)
    sB = cuda.shared.array(shape=(TPB, TPB), dtype=float32)

    x, y = cuda.grid(2)
    
    tx = cuda.threadIdx.x
    ty = cuda.threadIdx.y
    
    if x >= C.shape[0] and y >= C.shape[1]:
        # Quit if (x, y) is outside of valid C boundary
        return

    # Each thread computes one element in the result matrix.
    # The dot product is chunked into dot products of TPB-long vectors.
    tmp = 0.
    for i in range(int(A.shape[1] / TPB)):
        # Preload data into shared memory
        sA[tx, ty] = A[x, ty + i * TPB]
        sB[tx, ty] = B[tx + i * TPB, y]

        # Wait until all threads finish preloading
        cuda.syncthreads()

        # Computes partial product on the shared memory
        for j in range(TPB):
            tmp += sA[tx, j] * sB[j, ty]

        # Wait until all threads finish computing
        cuda.syncthreads()

    C[x, y] = tmp

# The data array
A = numpy.full((TPB*2, TPB*3), 3, numpy.float) # [32 x 48] matrix containing all 3's
B = numpy.full((TPB*3, TPB*1), 4, numpy.float) # [48 x 16] matrix containing all 4's

A_global_mem = cuda.to_device(A)
B_global_mem = cuda.to_device(B)
C_global_mem = cuda.device_array((TPB*2, TPB*1)) # [32 x 16] matrix result

# Configure the blocks
threadsperblock = (TPB, TPB)
blockspergrid_x = int(math.ceil(A.shape[0] / threadsperblock[1]))
blockspergrid_y = int(math.ceil(B.shape[1] / threadsperblock[0]))
blockspergrid = (blockspergrid_x, blockspergrid_y)

# Start the kernel 
fast_matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)
res = C_global_mem.copy_to_host()

print(res)
```

Code output when trying to run test.py from a godot-python python shell in the terminal.

```
# Code output from test.py
tobka@lindstrom:~/python_godot_3/addons/pythonscript/x11-64/bin$ ./python3 test.py 
Traceback (most recent call last):
  File "test.py", line 241, in <module>
    fast_matmul[blockspergrid, threadsperblock](A_global_mem, B_global_mem, C_global_mem)
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/compiler.py", line 769, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/compiler.py", line 861, in call
    kernel = self.compile(argtypes)
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/compiler.py", line 935, in compile
    kernel.bind()
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/compiler.py", line 576, in bind
    self._func.get()
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/compiler.py", line 446, in get
    ptx = self.ptx.get()
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/compiler.py", line 414, in get
    arch = nvvm.get_arch_option(*cc)
  File "/home/tobka/python_godot_3/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 345, in get_arch_option
    return 'compute_%d%d' % arch
TypeError: not enough arguments for format string
```

**Comment by touilleMan** [comment]
> TypeError: not enough arguments for format string

I guess this is related to https://github.com/numba/numba/issues/6223 (see also the related PR https://github.com/numba/numba/pull/6227), from what I understand this is most likely due to the fact your cudatoolkit  badly setup.

> Another symptom that I suspect is connected is that when I run an interactive shell of the godot-python python installation is that hitting backspace prints an empty space (it doesn't erase chars as expected, but appends empty space to the command line).

Yes the readline support is broken in the python interpreter shipped within godot-python. I don't think it's a big deal given you shouldn't be using this interpreter directly (it is there only to be able to use pip and to debug the installation, otherwise it is pretty useless given to have access to the Godot API you must use the godot binary instead)

**Comment by touilleMan** [comment]
(closing the issue given I don't think it's related to godot-python  directly, but feel free to add comments or even re-open if you consider I've missed something ^^)
