### ISSUE TITLE
Calling function with PoolByteArray results in TypeError

### ISSUE THREAD

**Issue by lihop** [touilleMan/godot-python#249]
Here is a minimal example:
```bash
# SceneTree
┖╴Node (node.gd)
   ┖╴PythonNode (python_node.py)
```
```python
# python_node.py
from godot import exposed, export
from godot import *

@exposed
class PythonNode(Node):
	def some_func(self, data):
		print('got data yay!')
```
```gdscript
# node.gd
extends Node

func _ready():
	$PythonNode.some_func(PoolIntArray()) # <- This works :)
	$PythonNode.some_func(PoolByteArray()) # <- This crashes!
```
Output:
```
Pythonscript 0.40.0 (CPython 3.8.5.final.0)
got data yay!
Traceback (most recent call last):
  File "build/x11-64/pythonscript/_godot_instance.pxi", line 97, in _godot.pythonscript_instance_call_method
  File "build/x11-64/pythonscript/godot/_hazmat/conversion.pyx", line 177, in godot._hazmat.conversion.godot_variant_to_pyobj
  File "build/x11-64/pythonscript/godot/_hazmat/conversion.pyx", line 300, in godot._hazmat.conversion._godot_variant_to_pyobj_pool_byte_array
TypeError: godot.pool_arrays.PoolByteArray.__new__(godot.pool_arrays.PoolIntArray): godot.pool_arrays.PoolIntArray is not a subtype of godot.pool_arrays.PoolByteArray
```

godot-python version: master (b9c239c8652c7a3fde18e66cb135c105b5d939c2)
Godot version: 3.2.3.stable.custom_build
OS version: NixOS 21.03.git.db8887e837cM (Okapi)

**Comment by touilleMan** [comment]
Good catch @lihop ;-)
#250 should fix this
