### ISSUE TITLE
No such file godot/modules/gdnative/godot.h when building on macos

### ISSUE THREAD

**Issue by romantolkachyov** [touilleMan/godot-python#30]
I'm trying to build godot-python under macos. I've got following error:

```
╰─ make generate_gdnative_cffidefs
/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py --output /Users/roman/work/godot-python/pythonscript/cffi_bindings/cdef.gen.h /Users/roman/work/godot-python/godot
clang: error: no such file or directory: '/Users/roman/work/godot-python/godot/modules/gdnative/godot.h'
clang: error: no input files
Traceback (most recent call last):
  File "/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py", line 61, in <module>
    fd.write(generate(args.godot_root_path))
  File "/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py", line 47, in generate
    first_line = next(i for i, line in enumerate(splitted_src) if 'godot' in line.lower())
StopIteration
make: *** [generate_gdnative_cffidefs] Error 1
```

I tried to change `gdnative/godot.h` to `gdnative/gdnative.h` but it cause other strange errors like:

```
╰─ make generate_gdnative_cffidefs
/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py --output /Users/roman/work/godot-python/pythonscript/cffi_bindings/cdef.gen.h /Users/roman/work/godot-python/godot
In file included from /Users/roman/work/godot-python/godot/modules/gdnative/godot/gdnative.h:50:
/usr/include/TargetConditionals.h:269:6: error: #elif after #else
    #elif defined(TARGET_CPU_PPC64) && TARGET_CPU_PPC64
     ^
/usr/include/TargetConditionals.h:279:6: error: #elif after #else
    #elif defined(TARGET_CPU_X86) && TARGET_CPU_X86
     ^
/usr/include/TargetConditionals.h:289:6: error: #elif after #else
    #elif defined(TARGET_CPU_X86_64) && TARGET_CPU_X86_64
     ^
/usr/include/TargetConditionals.h:299:6: error: #elif after #else
    #elif defined(TARGET_CPU_ARM) && TARGET_CPU_ARM
     ^
/usr/include/TargetConditionals.h:309:6: error: #elif after #else
    #elif defined(TARGET_CPU_ARM64) && TARGET_CPU_ARM64
     ^
/usr/include/TargetConditionals.h:319:6: error: #else after #else
    #else
     ^
/usr/include/TargetConditionals.h:369:2: error: #endif without #if
#endif
 ^
/usr/include/TargetConditionals.h:371:2: error: #endif without #if
#endif  /* __TARGETCONDITIONALS__ */
 ^
/Users/roman/work/godot-python/godot/modules/gdnative/godot/gdnative.h:97:31: warning: missing
      terminating ' character [-Winvalid-pp-token]
        GODOT_ERR_CANT_OPEN, ///< Can't open a resource/socket/file
                                     ^
In file included from /Users/roman/work/godot-python/godot/modules/gdnative/godot/gdnative.h:177:
In file included from /Users/roman/work/godot-python/godot/modules/gdnative/godot/string.h:38:
In file included from /usr/include/wchar.h:72:
In file included from /usr/include/Availability.h:190:
/usr/include/AvailabilityInternal.h:22938:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_12
         ^
/usr/include/AvailabilityInternal.h:22867:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_4
         ^
/usr/include/AvailabilityInternal.h:22800:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_3
         ^
/usr/include/AvailabilityInternal.h:22737:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_2
         ^
/usr/include/AvailabilityInternal.h:22678:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11
         ^
/usr/include/AvailabilityInternal.h:22623:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_10_3
         ^
/usr/include/AvailabilityInternal.h:22572:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_10_2
         ^
/usr/include/AvailabilityInternal.h:22525:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_10
         ^
/usr/include/AvailabilityInternal.h:22482:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_9
         ^
/usr/include/AvailabilityInternal.h:22443:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_8
         ^
/usr/include/AvailabilityInternal.h:22408:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_7
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
Traceback (most recent call last):
  File "/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py", line 61, in <module>
    fd.write(generate(args.godot_root_path))
  File "/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py", line 41, in generate
    ast = parse_file(gdnative_header, use_cpp=True, cpp_args=['-D__attribute__(x)=', '-I' + gdnative_include, '-I%sfake_libc_include' % BASEDIR])
  File "/Users/roman/work/godot-python/tools/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/Users/roman/work/godot-python/tools/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Users/roman/work/godot-python/tools/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/roman/work/godot-python/tools/pycparser/ply/yacc.py", line 1118, in parseopt_notrack
    p.callable(pslice)
  File "/Users/roman/work/godot-python/tools/pycparser/c_parser.py", line 566, in p_pp_directive
    self._token_coord(p, 1))
  File "/Users/roman/work/godot-python/tools/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: /usr/include/TargetConditionals.h:95:5: Directives not supported yet
make: *** [generate_gdnative_cffidefs] Error 1
```

Can anyone help with this problems?

**Comment by romantolkachyov** [comment]
I've tried to follow second way (replacing `gdnative/godot.h` with `gdnative/gdnative.h`). But now I end up with the following errors:

```
In file included from /Users/roman/work/godot-python/godot/modules/gdnative/gdnative.h:33:
In file included from godot/core/io/resource_loader.h:33:
In file included from godot/core/resource.h:33:
In file included from godot/core/class_db.h:33:
godot/core/method_bind.h:346:10: fatal error: 'method_bind.gen.inc' file not found
#include "method_bind.gen.inc"
         ^
79 warnings and 12 errors generated.
Traceback (most recent call last):
  File "/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py", line 61, in <module>
    fd.write(generate(args.godot_root_path))
  File "/Users/roman/work/godot-python/tools/generate_gdnative_cffidefs.py", line 41, in generate
    ast = parse_file(gdnative_header, use_cpp=True, cpp_args=['-D__attribute__(x)=', '-I' + gdnative_include, '-I%s/fake_libc_include' % BASEDIR, '-Igodot', '-Igodot/core', '-Igodot/core/math', '-Igodot/platform/osx'])
  File "/Users/roman/work/godot-python/tools/pycparser/__init__.py", line 93, in parse_file
    return parser.parse(text, filename)
  File "/Users/roman/work/godot-python/tools/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Users/roman/work/godot-python/tools/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/roman/work/godot-python/tools/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/roman/work/godot-python/tools/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/roman/work/godot-python/tools/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Users/roman/work/godot-python/tools/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: godot/core/error_list.h:42:10: before: /
make: *** [generate_gdnative_cffidefs] Error 1
```

I can't found `method_bind.gen.inc` file in project. Where I can get it? Seems like `pythonscript/cffi_bindings/generate.py` do so but it fails too:

```
╰─ python pythonscript/cffi_bindings/generate.py
Traceback (most recent call last):
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/cparser.py", line 269, in _parse
    ast = _get_parser().parse(csource)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :28:2: before: godot_string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pythonscript/cffi_bindings/generate.py", line 111, in <module>
    """ + cdef + strip_hashed_src(api_struct_src))
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/api.py", line 106, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/api.py", line 120, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/cparser.py", line 308, in parse
    self._internal_parse(csource)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/cparser.py", line 313, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/cparser.py", line 271, in _parse
    self.convert_pycparser_error(e, csource)
  File "/Users/roman/virtualenvs/godot/lib/python3.6/site-packages/cffi/cparser.py", line 300, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "godot_string name;"
:28:2: before: godot_string
```

**Comment by touilleMan** [comment]
Hi !
Godot has just renamed it GDnative module headers so the generation script is broken.
I've just updated the master branch to fix that ;-)

**Comment by kureta** [comment]
I am still having a similar issue. I have compiled the code and now trying to run the example project like this:

`$ scons platform=osx-64 backend=cpython gdnative_parse_cpp="clang -E" example`

and the result is

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
. tools/venv/bin/activate && python ./pythonscript/generate_cffi_bindings.py --cdef=pythonscript/cdef.gen.h --output=pythonscript/cffi_bindings.gen.c
Traceback (most recent call last):
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/cparser.py", line 276, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/pycparser/c_parser.py", line 152, in parse
    debug=debuglevel)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/pycparser/c_parser.py", line 1761, in p_error
    column=self.clex.find_tok_column(p)))
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/pycparser/plyparser.py", line 66, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:23:2: before: godot_string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pythonscript/generate_cffi_bindings.py", line 106, in <module>
    generate_cffi_bindings(args.output, args.cdef, args.dev_dyn)
  File "./pythonscript/generate_cffi_bindings.py", line 90, in generate_cffi_bindings
    """ + cdef + strip_hashed_src(api_struct_src))
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/api.py", line 107, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/cparser.py", line 320, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/cparser.py", line 278, in _parse
    self.convert_pycparser_error(e, csource)
  File "/Users/kureta/.pyenv/versions/default/lib/python3.6/site-packages/cffi/cparser.py", line 307, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "godot_string name;"
<cdef source string>:23:2: before: godot_string
scons: *** [pythonscript/cffi_bindings.gen.c] Error 1
scons: building terminated because of errors.
```

**Comment by kureta** [comment]
Cleaning worked, thank you. Now I have loaded the project on my Godot installation (on MacOS). I can play it within Godot editor. But if I export a `.app` application it crashes. I can see the following error in the terminal

```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```

**Comment by touilleMan** [comment]
Exporting a godot project with python is not supported yet
I guess you could do this by tweaking the pluginscript.gdns file (the
documentation on this part of GDnative is currently lacking, but @karroffel
is working hard on it ^_^)

If you do this, please keep me informed ;-)
