### ISSUE TITLE
get_children() not working when Label3D is a child.

### ISSUE THREAD

**Issue by MarioMey** [touilleMan/godot-python#379]
Godot v3.5.stable.official [991bb6ac7]
Maybe this is because Label3D is a new type of object and it is not in object types list somewhere?
```
Pythonscript 0.50.0 (CPython 3.8.5.final.0)
Traceback (most recent call last):
  File "build/x11-64/pythonscript/_godot_instance.pxi", line 98, in _godot.pythonscript_instance_call_method
  File "/home/mariomey/md-godot/test_godot_3.5/cubo_armature.py", line 24, in _ready
    print(self.get_children())
  File "build/x11-64/pythonscript/godot/builtins.pyx", line 3018, in godot.builtins.Array.__repr__
  File "build/x11-64/pythonscript/godot/builtins.pyx", line 3080, in __iter__
  File "build/x11-64/pythonscript/godot/builtins.pyx", line 3185, in godot.builtins.Array.get
  File "build/x11-64/pythonscript/godot/_hazmat/conversion.pyx", line 168, in godot._hazmat.conversion.godot_variant_to_pyobj
  File "build/x11-64/pythonscript/godot/_hazmat/conversion.pyx", line 284, in godot._hazmat.conversion._godot_variant_to_pyobj_object
  File "build/x11-64/pythonscript/godot/bindings.pyx", line 198, in godot.bindings.Object.cast_from_variant
KeyError: 'Label3D'
```
Can this be fixed... in this version 3.5? Pleeeaaseee...? 😁

**Comment by jdrempel** [comment]
Same problem when trying to iterate children of a `GraphEdit`:
```
Traceback (most recent call last):
  File "build/x11-64/pythonscript/_godot_instance.pxi", line 98, in _godot.pythonscript_instance_call_method
  File "$HOME/projects/project/Graph.py", line 351, in _physics_process
    self._step_flow_simulation(ConnectionType.POWER)
  File "$HOME/projects/project/Graph.py", line 122, in _step_flow_simulation
    for node in self.get_powered_children():
  File "$HOME/projects/project/Graph.py", line 105, in get_powered_children
    for child in self.get_children():
  File "build/x11-64/pythonscript/godot/builtins.pyx", line 3080, in __iter__
  File "build/x11-64/pythonscript/godot/builtins.pyx", line 3185, in godot.builtins.Array.get
  File "build/x11-64/pythonscript/godot/_hazmat/conversion.pyx", line 168, in godot._hazmat.conversion.godot_variant_to_pyobj
  File "build/x11-64/pythonscript/godot/_hazmat/conversion.pyx", line 284, in godot._hazmat.conversion._godot_variant_to_pyobj_object
  File "build/x11-64/pythonscript/godot/bindings.pyx", line 198, in godot.bindings.Object.cast_from_variant
KeyError: 'GraphEditFilter'
```
