### ISSUE TITLE
make generate_gdnative_cffidefs fails with current master branch of godot

### ISSUE THREAD

**Issue by benhuber** [touilleMan/godot-python#38]
This project is meant for Godot 3.0, is it not? It is possible that I made a mistake, but it seems to me, that it is not up to date with Godots gdnative sourcecode.
````
$ make generate_gdnative_cffidefs
/home/X/code/godot-python/tools/generate_gdnative_cffidefs.py --output /home/X/code/godot-python/pythonscript/cffi_bindings/cdef.gen.h /home/X/code/godot-python/godot
cpp: error: /home/X/code/godot-python/godot/modules/gdnative/godot/gdnative.h: No such file or directory
cpp: warning: ‘-x c’ after last input file has no effect
cpp: fatal error: no input files
compilation terminated.
Traceback (most recent call last):
  File "/home/X/code/godot-python/tools/generate_gdnative_cffidefs.py", line 61, in <module>
    fd.write(generate(args.godot_root_path))
  File "/home/X/code/godot-python/tools/generate_gdnative_cffidefs.py", line 47, in generate
    first_line = next(i for i, line in enumerate(splitted_src) if 'godot' in line.lower())
StopIteration
make: *** [Makefile:117: generate_gdnative_cffidefs] Error 1
$ ls godot/modules/gdnative/
total 2.9M
4.0K config.py           20K gdnative_api_struct.gen.cpp             4.0K gd_native_library_editor.h               4.0K nativescript/                  8.0K SCsub
4.0K config.pyc         200K gdnative_api_struct.gen.x11.tools.64.o  764K gd_native_library_editor.x11.tools.64.o  4.0K pluginscript/
4.0K doc_classes/        12K gdnative.cpp                            968K gdnative.x11.tools.64.o                   12K register_types.cpp
4.0K gdnative/          8.0K gdnative.h                              4.0K include/                                 4.0K register_types.h
132K gdnative_api.json  8.0K gd_native_library_editor.cpp            4.0K nativearvr/                              708K register_types.x11.tools.64.o

````
As you see, the 'godot' subfolder inside 'gdnative' does not exist.

**Comment by touilleMan** [comment]
Do you use the `pluginscript` branch ? The GDnative folder evolved a lot until recently, so it's likely the project is not up-to-date with it.
I currently don't have time to work on this, but I plan to do that and have a proper release of the module on the asset store eventually.

**Comment by benhuber** [comment]
No, I just followed the instructions from the readme and thus used the master branch. It seems to work with the pluginscript branch =)

**Comment by touilleMan** [comment]
cool ;-)
